### ISSUE TITLE
Publishing on flathub

### ISSUE THREAD

**Issue by albfan** [DaveDavenport/gpx-viewer#11]
You can review here:

https://github.com/flathub/flathub/pull/2497

there's an open question about why session-bus permission is needed.

**Comment by DaveDavenport** [comment]
I don't exactly know, long time ago I wrote this.
If I remember correctly it uses GtkApplication to keep one unique instance, instead of launching multiple.

**Comment by albfan** [comment]
Can we tag 0.3.0, 0.4.0 tags? that will make easy to release (we can use a commit in other case)

**Comment by DaveDavenport** [comment]
Is it release ready?

**Comment by albfan** [comment]
Probably there're other deprecations to fix, but looks stable enough. Maybe tag a version 0.4.1 or 0.5.0 and set a roadmap for 1.0 or 0.6.0

**Comment by albfan** [comment]
Done! https://flathub.org/apps/details/nl.sarine.gpx-viewer
