### ISSUE TITLE
Full migration to vala

### ISSUE THREAD

**Issue by albfan** [DaveDavenport/gpx-viewer#17]
Any reason to keep gpx-viewer in C? Looks easily portable to vala

**Comment by DaveDavenport** [comment]
No, when I wrote this vala was a lot less mature as a language and the bindings where still very buggy.
At that point there where several things that did not work yet, so I kept it in C.

I don't expect this to be an issue anymore 11-12? years later?

**Comment by albfan** [comment]
Fair enough. I was adding keyboard shortcuts, and is easy to do.

Signaling is a little bit more complex, but not really needed, just a better way to avoid coupling components
