### ISSUE TITLE
What is manager for?

### ISSUE THREAD

**Issue by albfan** [DaveDavenport/gpx-viewer#18]
How is manager supposed to be used?

Should it be moved to it's own project?

https://github.com/DaveDavenport/gpx-viewer/tree/0.4.0/manager

**Comment by DaveDavenport** [comment]
I think it was mosty code  I wrote testing out stuff, but it been many years ago :smile:

**Comment by albfan** [comment]
Yes, looks like. Let's see if it has any extra feature, if there's nothing there we can remove it
