### ISSUE TITLE
verify app on flathub

### ISSUE THREAD

**Issue by albfan** [DaveDavenport/gpx-viewer#38]
Flathub request this to verify the app:

Create a page at https://sarine.nl/.well-known/org.flathub.VerifiedApps.txt containing the following token:

cbfec812-01eb-4894-a2c2-595152db6379

There's only active  https://blog.sarine.nl, so probably we can modify that url to have the file at correct place

Example from gnome apps:

https://gnome.org/.well-known/org.flathub.VerifiedApps.txt 

@DaveDavenport  do you think we can add that? I will work to fix the url website

**Comment by DaveDavenport** [comment]
Added the orig url..: https://sarine.nl/.well-known/org.flathub.VerifiedApps.txt

**Comment by albfan** [comment]
Yep, done!
